services:
  - type: web
    name: stegx-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python backend/main.py"
    envVars:
      - key: PORT
        value: 10000
